# Generated by Django 5.2.13 on 2026-04-13 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_name', models.CharField(max_length=150)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('about_text', models.TextField()),
                ('address', models.TextField()),
                ('primary_phone', models.CharField(max_length=30)),
                ('secondary_phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('working_hours_summary', models.CharField(blank=True, max_length=255)),
                ('hero_title', models.CharField(max_length=150)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('hero_cta_text', models.CharField(blank=True, max_length=80)),
                ('hero_cta_url', models.CharField(blank=True, max_length=255)),
                ('location_embed_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='core.sitesettings')),
            ],
            options={
                'ordering': ['sort_order', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='BusinessHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('label', models.CharField(max_length=40)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='core.sitesettings')),
            ],
            options={
                'ordering': ['sort_order', 'day_of_week'],
                'unique_together': {('site_settings', 'day_of_week')},
            },
        ),
    ]
