# Generated by Django 5.2.13 on 2026-04-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesshour',
            name='label_ar',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_cta_text_ar',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_ar',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='store_name_ar',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_ar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='working_hours_summary_ar',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
