# Generated by Django 5.2.13 on 2026-04-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='dollar_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
