# Generated by Django 5.2.13 on 2026-04-16 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_dollar_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='free_delivery_radius_km',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=6),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='store_map_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='store_map_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='confirmed', max_length=20)),
                ('address_snapshot', models.TextField()),
                ('subtotal_min', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal_max', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_min', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_max', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('route_source', models.CharField(blank=True, max_length=30)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.customeraddress')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.customerprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('category_label', models.CharField(blank=True, max_length=120)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_label', models.CharField(blank=True, max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total_min', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total_max', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_weight_based', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.customerorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
