# Generated by Codex on 2026-04-22

import django.db.models.deletion
from django.db import migrations, models


def migrate_address_areas(apps, schema_editor):
    DeliveryArea = apps.get_model("core", "DeliveryArea")
    CustomerAddress = apps.get_model("core", "CustomerAddress")
    for address in CustomerAddress.objects.all():
        area_name = (getattr(address, "area_name", "") or "Default Area").strip() or "Default Area"
        area, _ = DeliveryArea.objects.get_or_create(
            name=area_name,
            defaults={
                "delivery_fee": 0,
                "display_order": 0,
                "is_active": True,
            },
        )
        address.area_id = area.pk
        address.save(update_fields=["area"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_sitesettings_delivery_fee_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryArea",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("delivery_fee", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="deliveryarea",
            index=models.Index(fields=["is_active", "display_order"], name="core_delive_is_acti_493f15_idx"),
        ),
        migrations.AddField(
            model_name="customeraddress",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="addresses",
                to="core.deliveryarea",
            ),
        ),
        migrations.AddField(
            model_name="customeraddress",
            name="apartment",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="customeraddress",
            name="building",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="customeraddress",
            name="nearby_landmark",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="customeraddress",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(migrate_address_areas, noop_reverse),
        migrations.AlterField(
            model_name="customeraddress",
            name="area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="addresses",
                to="core.deliveryarea",
            ),
        ),
        migrations.RemoveField(model_name="customeraddress", name="area_name"),
        migrations.RemoveField(model_name="customeraddress", name="map_pin_latitude"),
        migrations.RemoveField(model_name="customeraddress", name="map_pin_longitude"),
        migrations.RemoveField(model_name="sitesettings", name="delivery_fee"),
        migrations.RemoveField(model_name="sitesettings", name="free_delivery_radius_km"),
        migrations.RemoveField(model_name="sitesettings", name="location_embed_url"),
        migrations.RemoveField(model_name="sitesettings", name="store_map_latitude"),
        migrations.RemoveField(model_name="sitesettings", name="store_map_longitude"),
        migrations.AddField(
            model_name="customerorder",
            name="service_type",
            field=models.CharField(
                choices=[("pickup", "Pickup"), ("delivery", "Delivery")],
                default="delivery",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customerorder",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="core.customeraddress",
            ),
        ),
        migrations.RemoveField(model_name="customerorder", name="distance_km"),
        migrations.RemoveField(model_name="customerorder", name="route_source"),
    ]
