# Generated by Django 5.2.13 on 2026-05-06 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_customerorder_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='print_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='print_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='print_status',
            field=models.CharField(choices=[('not_sent', 'Not sent'), ('sent', 'Sent'), ('printed', 'Printed'), ('failed', 'Failed')], default='not_sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='status',
            field=models.CharField(choices=[('waiting_due_to_busy_center', 'Waiting due to busy center'), ('accepted', 'Accepted'), ('waiting_accept', 'Waiting for accept'), ('being_prepared', 'Preparing'), ('out_for_delivery', 'Out for delivery'), ('ready_to_pickup', 'Ready to pick up'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='waiting_accept', max_length=32),
        ),
        migrations.CreateModel(
            name='CenterStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy')], default='available', max_length=20)),
                ('busy_until', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='center_status_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Center status',
                'verbose_name_plural': 'Center status',
            },
        ),
    ]
