# Generated by Django 5.2.13 on 2026-05-27 11:10

from decimal import Decimal, ROUND_HALF_UP

from django.db import migrations, models


MONEY_FIELDS_BY_MODEL = {
    "SiteSettings": ("dollar_price",),
    "DeliveryArea": ("delivery_fee",),
    "DeliverySubArea": ("delivery_fee",),
    "CustomerOrder": (
        "subtotal_min",
        "subtotal_max",
        "delivery_fee",
        "total_min",
        "total_max",
    ),
    "CustomerOrderItem": ("unit_price", "line_total_min", "line_total_max"),
}


def round_money_fields(apps, schema_editor):
    for model_name, fields in MONEY_FIELDS_BY_MODEL.items():
        model = apps.get_model("core", model_name)
        for item in model.objects.all().only("pk", *fields):
            changed = []
            for field in fields:
                rounded = Decimal(getattr(item, field) or 0).quantize(
                    Decimal("1"),
                    rounding=ROUND_HALF_UP,
                )
                if getattr(item, field) != rounded:
                    setattr(item, field, rounded)
                    changed.append(field)
            if changed:
                item.save(update_fields=changed)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customerorder_print_attempted_at_and_more'),
    ]

    operations = [
        migrations.RunPython(round_money_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customerorder',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='subtotal_max',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='subtotal_min',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='total_max',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='total_min',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customerorderitem',
            name='line_total_max',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customerorderitem',
            name='line_total_min',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customerorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='deliveryarea',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deliverysubarea',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='dollar_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
