# Generated by Codex on 2026-06-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_company_grouped_products"),
        ("core", "0013_alter_customerorder_delivery_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerorderitem",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="catalog.productcompany",
            ),
        ),
        migrations.AddField(
            model_name="customerorderitem",
            name="company_label",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="customerorderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="customerorderitem",
            name="selected_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="catalog.productcompanyoption",
            ),
        ),
        migrations.AddField(
            model_name="customerorderitem",
            name="selected_option_label",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
