# Generated by Django 5.2.13 on 2026-04-13 16:45

import apps.promotions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('badge_text', models.CharField(blank=True, max_length=60)),
                ('cta_text', models.CharField(blank=True, max_length=60)),
                ('cta_url', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, upload_to=apps.promotions.models.promotion_upload_path)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'title'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='promotions__is_acti_1f85b9_idx'), models.Index(fields=['start_date', 'end_date'], name='promotions__start_d_283aa1_idx')],
            },
        ),
    ]
