# Generated by Django 5.2.13 on 2026-04-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='badge_text_ar',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='promotion',
            name='cta_text_ar',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='promotion',
            name='description_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='external_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='subtitle_ar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='promotion',
            name='title_ar',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
