# Generated by Django 5.2.13 on 2026-04-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_promotion_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='is_price_linked_to_dollar',
            field=models.BooleanField(default=False),
        ),
    ]
