# Generated by Django 5.2.13 on 2026-05-27 11:10

from decimal import Decimal, ROUND_HALF_UP

from django.db import migrations, models


def round_promotion_prices(apps, schema_editor):
    promotion = apps.get_model("promotions", "Promotion")
    for item in promotion.objects.all().only("pk", "price"):
        item.price = Decimal(item.price or 0).quantize(Decimal("1"), rounding=ROUND_HALF_UP)
        item.save(update_fields=["price"])


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_promotion_is_price_linked_to_dollar'),
    ]

    operations = [
        migrations.RunPython(round_promotion_prices, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='promotion',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
