# Generated by Django 5.2.13 on 2026-06-08 18:16

import apps.promotions.models
import media.utils.image_optimizer
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_alter_promotion_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=media.utils.image_optimizer.OptimizedImageField(blank=True, optimization_profile='banner', upload_to=apps.promotions.models.promotion_upload_path),
        ),
    ]
