# Generated by Django 5.2.13 on 2026-04-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_description_ar_category_external_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_price_linked_to_dollar',
            field=models.BooleanField(default=False),
        ),
    ]
