# Generated by Django 5.2.13 on 2026-04-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_is_price_linked_to_dollar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='sold_by_weight',
            field=models.BooleanField(default=False),
        ),
    ]
