# Generated by Codex on 2026-04-22

from django.db import migrations, models


def preserve_existing_product_overrides(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    Product.objects.filter(is_price_linked_to_dollar=True).update(price_link_mode="custom")
    Product.objects.filter(sold_by_weight=True).update(sold_by_weight_mode="custom")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_category_options_product_sold_by_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_price_linked_to_dollar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="category",
            name="sold_by_weight",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="price_link_mode",
            field=models.CharField(
                choices=[("inherit", "Inherit from category"), ("custom", "Custom product setting")],
                default="inherit",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sold_by_weight_mode",
            field=models.CharField(
                choices=[("inherit", "Inherit from category"), ("custom", "Custom product setting")],
                default="inherit",
                max_length=20,
            ),
        ),
        migrations.RunPython(preserve_existing_product_overrides, noop_reverse),
    ]
