# Generated by Django 5.2.13 on 2026-05-27 11:10

from decimal import Decimal, ROUND_HALF_UP

import django.core.validators
from django.db import migrations, models


def round_catalog_prices(apps, schema_editor):
    for model_name in ("Product", "ProductOption"):
        model = apps.get_model("catalog", model_name)
        for item in model.objects.all().only("pk", "price"):
            item.price = Decimal(item.price or 0).quantize(Decimal("1"), rounding=ROUND_HALF_UP)
            item.save(update_fields=["price"])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_has_options_alter_product_price_and_more'),
    ]

    operations = [
        migrations.RunPython(round_catalog_prices, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
