# Generated by Codex on 2026-05-31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_allow_decimal_product_prices"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="catalog.category",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_price_linked_to_dollar",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="sold_by_weight",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["parent", "is_active", "display_order"],
                name="catalog_cat_parent__618072_idx",
            ),
        ),
    ]
