# Generated by Codex on 2026-06-01

import django.core.validators
import django.db.models.deletion
import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_category_hierarchy"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("normal", "Normal product"),
                    ("company_grouped", "Company/brand grouped product"),
                ],
                default="normal",
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="ProductCompany",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("logo", models.ImageField(blank=True, upload_to=apps.catalog.models.company_upload_path)),
                ("external_logo_url", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companies",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product company",
                "verbose_name_plural": "Product companies",
                "ordering": ["order", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductCompanyOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="catalog.productcompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product company option",
                "verbose_name_plural": "Product company options",
                "ordering": ["order", "name", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="productcompany",
            index=models.Index(fields=["product", "is_active", "order"], name="catalog_pro_product_2630b6_idx"),
        ),
        migrations.AddIndex(
            model_name="productcompanyoption",
            index=models.Index(fields=["company", "is_available", "order"], name="catalog_pro_company_f0ca00_idx"),
        ),
    ]
