# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_company_grouped_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="productoption",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveIndex(
            model_name="productoption",
            name="catalog_pro_product_d9265a_idx",
        ),
        migrations.AddIndex(
            model_name="productoption",
            index=models.Index(
                fields=["product", "is_available", "display_order"],
                name="catalog_pro_product_a28ec5_idx",
            ),
        ),
    ]
