# Generated by Django 5.2.13 on 2026-06-08 18:16

import apps.catalog.models
import media.utils.image_optimizer
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_merge_legacy_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cover_image',
            field=media.utils.image_optimizer.OptimizedImageField(blank=True, optimization_profile='category', upload_to=apps.catalog.models.category_upload_path),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=media.utils.image_optimizer.OptimizedImageField(blank=True, optimization_profile='company', upload_to=apps.catalog.models.company_upload_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='primary_image',
            field=media.utils.image_optimizer.OptimizedImageField(blank=True, optimization_profile='product', upload_to=apps.catalog.models.product_upload_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=media.utils.image_optimizer.OptimizedImageField(optimization_profile='product', upload_to=apps.catalog.models.gallery_upload_path),
        ),
    ]
